# Generated by Django 5.0.6 on 2024-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('category_id', models.IntegerField()),
                ('product_photo_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
