# Generated by Django 5.0.6 on 2024-07-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categories_alter_products_brand_alter_products_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
