# Generated by Django 5.0.6 on 2024-07-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_id_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=13)),
                ('monday', models.CharField(max_length=300)),
                ('tuesday', models.CharField(max_length=300)),
                ('wednesday', models.CharField(max_length=300)),
                ('thursday', models.CharField(max_length=300)),
                ('friday', models.CharField(max_length=300)),
                ('saturday', models.CharField(max_length=300)),
                ('sunday', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceReport',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stores')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_Products',
            fields=[
                ('fav_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
